version: "3.8"

services:
  db:
     image: yandex/clickhouse-server
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144

  yandex:
    build: .
    environment:
      UBIC_URL: "http://ubic-mock:8888"
      CLICKHOUSE_URL: "db"
      AGGR_NAME: "Yandex"
      AGGR_UUID: "777aaaaa-1af0-489e-b761-d40344c12e70"
      
  city:
    build: .
    environment:
      UBIC_URL: "http://ubic-mock:8888"
      CLICKHOUSE_URL: "db"
      AGGR_NAME: "City"
      AGGR_UUID: "888aaaaa-1af0-489e-b761-d40344c12e70"
  
  gett:
    build: .
    environment:
      UBIC_URL: "http://ubic-mock:8888"
      CLICKHOUSE_URL: "db"
      AGGR_NAME: "Gett"
      AGGR_UUID: "999aaaaa-1af0-489e-b761-d40344c12e70"

networks:
  default:
    external:
      name: taxi-net
