version: "3"

services:
  db:
     image: yandex/clickhouse-server
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144

  yandex:
    build: .
    ports:
      - "9091:9090"
    environment:
      CLICK_HOUSE_URL: "db"
      AGGR_NAME: "Yandex"
      AGGR_UUID: "777aaaaa-1af0-489e-b761-d40344c12e70"
      
  city:
    build: .
    ports:
      - "9092:9090"
    environment:
      CLICK_HOUSE_URL: "db"
      AGGR_NAME: "City"
      AGGR_UUID: "888aaaaa-1af0-489e-b761-d40344c12e70"
  
  gett:
    build: .
    ports:
      - "9093:9090"
    environment:
      CLICK_HOUSE_URL: "db"
      AGGR_NAME: "Gett"
      AGGR_UUID: "999aaaaa-1af0-489e-b761-d40344c12e70"

networks:
  default:
    external:
      name: taxi-net
