# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_hash import DriverHash  # noqa: F401,E501
from swagger_server.models.single_data import SingleData  # noqa: F401,E501
from swagger_server import util


class DriverFatigue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hash_id: DriverHash=None, online: SingleData=None, on_order: SingleData=None):  # noqa: E501
        """DriverFatigue - a model defined in Swagger

        :param hash_id: The hash_id of this DriverFatigue.  # noqa: E501
        :type hash_id: DriverHash
        :param online: The online of this DriverFatigue.  # noqa: E501
        :type online: SingleData
        :param on_order: The on_order of this DriverFatigue.  # noqa: E501
        :type on_order: SingleData
        """
        self.swagger_types = {
            'hash_id': DriverHash,
            'online': SingleData,
            'on_order': SingleData
        }

        self.attribute_map = {
            'hash_id': 'hash_id',
            'online': 'online',
            'on_order': 'on_order'
        }
        self._hash_id = hash_id
        self._online = online
        self._on_order = on_order

    @classmethod
    def from_dict(cls, dikt) -> 'DriverFatigue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DriverFatigue of this DriverFatigue.  # noqa: E501
        :rtype: DriverFatigue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hash_id(self) -> DriverHash:
        """Gets the hash_id of this DriverFatigue.


        :return: The hash_id of this DriverFatigue.
        :rtype: DriverHash
        """
        return self._hash_id

    @hash_id.setter
    def hash_id(self, hash_id: DriverHash):
        """Sets the hash_id of this DriverFatigue.


        :param hash_id: The hash_id of this DriverFatigue.
        :type hash_id: DriverHash
        """

        self._hash_id = hash_id

    @property
    def online(self) -> SingleData:
        """Gets the online of this DriverFatigue.


        :return: The online of this DriverFatigue.
        :rtype: SingleData
        """
        return self._online

    @online.setter
    def online(self, online: SingleData):
        """Sets the online of this DriverFatigue.


        :param online: The online of this DriverFatigue.
        :type online: SingleData
        """

        self._online = online

    @property
    def on_order(self) -> SingleData:
        """Gets the on_order of this DriverFatigue.


        :return: The on_order of this DriverFatigue.
        :rtype: SingleData
        """
        return self._on_order

    @on_order.setter
    def on_order(self, on_order: SingleData):
        """Sets the on_order of this DriverFatigue.


        :param on_order: The on_order of this DriverFatigue.
        :type on_order: SingleData
        """

        self._on_order = on_order
