# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_fatigue import DriverFatigue  # noqa: F401,E501
from swagger_server import util


class FatigueBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, drivers: List[DriverFatigue]=None):  # noqa: E501
        """FatigueBody - a model defined in Swagger

        :param timestamp: The timestamp of this FatigueBody.  # noqa: E501
        :type timestamp: datetime
        :param drivers: The drivers of this FatigueBody.  # noqa: E501
        :type drivers: List[DriverFatigue]
        """
        self.swagger_types = {
            'timestamp': datetime,
            'drivers': List[DriverFatigue]
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'drivers': 'drivers'
        }
        self._timestamp = timestamp
        self._drivers = drivers

    @classmethod
    def from_dict(cls, dikt) -> 'FatigueBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FatigueBody of this FatigueBody.  # noqa: E501
        :rtype: FatigueBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this FatigueBody.

        timestamp, от которого отсчитываются соответствующие времена на линиии и на заказе.  # noqa: E501

        :return: The timestamp of this FatigueBody.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this FatigueBody.

        timestamp, от которого отсчитываются соответствующие времена на линиии и на заказе.  # noqa: E501

        :param timestamp: The timestamp of this FatigueBody.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def drivers(self) -> List[DriverFatigue]:
        """Gets the drivers of this FatigueBody.

        информация о времени \"на линии\" и на заказах водителей  # noqa: E501

        :return: The drivers of this FatigueBody.
        :rtype: List[DriverFatigue]
        """
        return self._drivers

    @drivers.setter
    def drivers(self, drivers: List[DriverFatigue]):
        """Sets the drivers of this FatigueBody.

        информация о времени \"на линии\" и на заказах водителей  # noqa: E501

        :param drivers: The drivers of this FatigueBody.
        :type drivers: List[DriverFatigue]
        """

        self._drivers = drivers
