# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_single_data import DriverSingleData  # noqa: F401,E501
from swagger_server import util


class HourResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, drivers: List[DriverSingleData]=None):  # noqa: E501
        """HourResponse - a model defined in Swagger

        :param drivers: The drivers of this HourResponse.  # noqa: E501
        :type drivers: List[DriverSingleData]
        """
        self.swagger_types = {
            'drivers': List[DriverSingleData]
        }

        self.attribute_map = {
            'drivers': 'drivers'
        }
        self._drivers = drivers

    @classmethod
    def from_dict(cls, dikt) -> 'HourResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HourResponse of this HourResponse.  # noqa: E501
        :rtype: HourResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def drivers(self) -> List[DriverSingleData]:
        """Gets the drivers of this HourResponse.

        массив структур вида [{hash_id, online}, ...]  # noqa: E501

        :return: The drivers of this HourResponse.
        :rtype: List[DriverSingleData]
        """
        return self._drivers

    @drivers.setter
    def drivers(self, drivers: List[DriverSingleData]):
        """Sets the drivers of this HourResponse.

        массив структур вида [{hash_id, online}, ...]  # noqa: E501

        :param drivers: The drivers of this HourResponse.
        :type drivers: List[DriverSingleData]
        """

        self._drivers = drivers
