# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_quad_data import DriverQuadData  # noqa: F401,E501
from swagger_server import util


class QuartersResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, drivers: List[DriverQuadData]=None):  # noqa: E501
        """QuartersResponse - a model defined in Swagger

        :param drivers: The drivers of this QuartersResponse.  # noqa: E501
        :type drivers: List[DriverQuadData]
        """
        self.swagger_types = {
            'drivers': List[DriverQuadData]
        }

        self.attribute_map = {
            'drivers': 'drivers'
        }
        self._drivers = drivers

    @classmethod
    def from_dict(cls, dikt) -> 'QuartersResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QuartersResponse of this QuartersResponse.  # noqa: E501
        :rtype: QuartersResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def drivers(self) -> List[DriverQuadData]:
        """Gets the drivers of this QuartersResponse.

        массив структур вида [{hash_id, {online, online, online, online}, ...]  # noqa: E501

        :return: The drivers of this QuartersResponse.
        :rtype: List[DriverQuadData]
        """
        return self._drivers

    @drivers.setter
    def drivers(self, drivers: List[DriverQuadData]):
        """Sets the drivers of this QuartersResponse.

        массив структур вида [{hash_id, {online, online, online, online}, ...]  # noqa: E501

        :param drivers: The drivers of this QuartersResponse.
        :type drivers: List[DriverQuadData]
        """

        self._drivers = drivers
