# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_hash import DriverHash  # noqa: F401,E501
from swagger_server import util


class TimeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, drivers: List[DriverHash]=None):  # noqa: E501
        """TimeRequest - a model defined in Swagger

        :param timestamp: The timestamp of this TimeRequest.  # noqa: E501
        :type timestamp: datetime
        :param drivers: The drivers of this TimeRequest.  # noqa: E501
        :type drivers: List[DriverHash]
        """
        self.swagger_types = {
            'timestamp': datetime,
            'drivers': List[DriverHash]
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'drivers': 'drivers'
        }
        self._timestamp = timestamp
        self._drivers = drivers

    @classmethod
    def from_dict(cls, dikt) -> 'TimeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimeRequest of this TimeRequest.  # noqa: E501
        :rtype: TimeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this TimeRequest.

        timestamp, от которого отсчитываются соответствующие времена на линиии и на заказе.  # noqa: E501

        :return: The timestamp of this TimeRequest.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this TimeRequest.

        timestamp, от которого отсчитываются соответствующие времена на линиии и на заказе.  # noqa: E501

        :param timestamp: The timestamp of this TimeRequest.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def drivers(self) -> List[DriverHash]:
        """Gets the drivers of this TimeRequest.

        массив хешей водителей  # noqa: E501

        :return: The drivers of this TimeRequest.
        :rtype: List[DriverHash]
        """
        return self._drivers

    @drivers.setter
    def drivers(self, drivers: List[DriverHash]):
        """Sets the drivers of this TimeRequest.

        массив хешей водителей  # noqa: E501

        :param drivers: The drivers of this TimeRequest.
        :type drivers: List[DriverHash]
        """

        self._drivers = drivers
