# coding: utf-8

"""
    Taxi Aggregator DB Service

    обращения операторов Такси к БД водителей.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v1_drivers_fatigue_post(self, body, **kwargs):  # noqa: E501
        """фиксировани усталости водителй  # noqa: E501

        приём (запись) данных о времени \"на линии\" и время на заказе для каждого водителя из заданного подможества  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_fatigue_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param FatigueBody body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_drivers_fatigue_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_drivers_fatigue_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def v1_drivers_fatigue_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """фиксировани усталости водителй  # noqa: E501

        приём (запись) данных о времени \"на линии\" и время на заказе для каждого водителя из заданного подможества  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_fatigue_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param FatigueBody body: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_drivers_fatigue_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_drivers_fatigue_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/drivers/fatigue', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_drivers_on_order_post(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на заказе\" для группы водителей  # noqa: E501

        были ли водители на заказе в течение часа с момента __timestamp__  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_on_order_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: QuartersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_drivers_on_order_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_drivers_on_order_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def v1_drivers_on_order_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на заказе\" для группы водителей  # noqa: E501

        были ли водители на заказе в течение часа с момента __timestamp__  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_on_order_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: QuartersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_drivers_on_order_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_drivers_on_order_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/drivers/on_order', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QuartersResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_drivers_online_hourly_post(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на линии\" (online) для группы водителей.  # noqa: E501

        были ли водители на линии в течение часа с момента __timestamp__  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_online_hourly_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: HourResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_drivers_online_hourly_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_drivers_online_hourly_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def v1_drivers_online_hourly_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на линии\" (online) для группы водителей.  # noqa: E501

        были ли водители на линии в течение часа с момента __timestamp__  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_online_hourly_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: HourResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_drivers_online_hourly_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_drivers_online_hourly_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/drivers/online/hourly', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='HourResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_drivers_online_quater_hourly_post(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на линии\" (online) для группы водителей  # noqa: E501

        были ли водители на линии в течение часа с момента __timestamp__ с информацией на каждые 15 мин  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_online_quater_hourly_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: QuartersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.v1_drivers_online_quater_hourly_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_drivers_online_quater_hourly_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def v1_drivers_online_quater_hourly_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Получение информации \"на линии\" (online) для группы водителей  # noqa: E501

        были ли водители на линии в течение часа с момента __timestamp__ с информацией на каждые 15 мин  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.v1_drivers_online_quater_hourly_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TimeRequest body: (required)
        :return: QuartersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_drivers_online_quater_hourly_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `v1_drivers_online_quater_hourly_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/drivers/online/quater_hourly', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QuartersResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
