# coding: utf-8

"""
    Taxi Aggregator DB Service

    обращения операторов Такси к БД водителей.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.driver_hash import DriverHash  # noqa: E501
from swagger_client.rest import ApiException


class TestDriverHash(unittest.TestCase):
    """DriverHash unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDriverHash(self):
        """Test DriverHash"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.driver_hash.DriverHash()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
