# coding: utf-8

"""
    Taxi Aggregator DB Service

    обращения операторов Такси к БД водителей.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_drivers_fatigue_post(self):
        """Test case for v1_drivers_fatigue_post

        фиксировани усталости водителй  # noqa: E501
        """
        pass

    def test_v1_drivers_on_order_post(self):
        """Test case for v1_drivers_on_order_post

        Получение информации \"на заказе\" для группы водителей  # noqa: E501
        """
        pass

    def test_v1_drivers_online_hourly_post(self):
        """Test case for v1_drivers_online_hourly_post

        Получение информации \"на линии\" (online) для группы водителей.  # noqa: E501
        """
        pass

    def test_v1_drivers_online_quater_hourly_post(self):
        """Test case for v1_drivers_online_quater_hourly_post

        Получение информации \"на линии\" (online) для группы водителей  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
