# coding: utf-8

"""
    Taxi Aggregator DB Service

    обращения операторов Такси к БД водителей.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.time_request import TimeRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestTimeRequest(unittest.TestCase):
    """TimeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeRequest(self):
        """Test TimeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.time_request.TimeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
